# Metricas de evaluación

Se muestran métricas de los modelos que tuvieron mejor desempeño para cada dataset.

In [1]:
import sys
import os

# Agregar el directorio raiz al PYTHONPATH
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
import pandas as pd
from constants.constants_tiktok import METRICS_DIR as TIKTOK_METRICS
from constants.constants_twitter import METRICS_DIR as TWITTER_METRICS

def compare_metrics(dir: str):
    df_best = []
    for filename in os.listdir(dir):
        if filename.endswith(".csv"):
            # Leer csv
            df = pd.read_csv(os.path.join(dir, filename))
            df = df[['model', 'accuracy', 'precision', 'recall', 'f1_score', 'name', 'train_time']]
            df = df.loc[df['accuracy'].idxmax()]
            df_best.append(df)
    df_final = pd.DataFrame(df_best).reset_index(drop=True)
    df_final = df_final.sort_values(by='accuracy', ascending=False)
    return df_final

print("TIKTOK METRICS")
display(compare_metrics(TIKTOK_METRICS))
print("TWITTER METRICS")
display(compare_metrics(TWITTER_METRICS))

TIKTOK METRICS

      model  accuracy  precision    recall  f1_score          name  train_time
0        LR  0.695445   0.700920  0.695433  0.697060       model_7   12.335266
5       SVM  0.693406   0.706100  0.693413  0.695798       model_6   13.947138
1      LSTM  0.679810   0.684370  0.679801  0.681126      model_16  125.163693
3        NB  0.665534   0.664144  0.665452  0.652540      model_35    0.146575
6      SWEM  0.664174   0.661793  0.664133  0.661956  svm_model_19   21.687140
2  MLP SWEM  0.652277   0.652602  0.652255  0.649874      model_27   17.538045
4       RNN  0.632223   0.630227  0.632175  0.628237       model_8   91.406702

TWITTER METRICS

      model  accuracy  precision    recall  f1_score          name  train_time
5       SVM  0.951725   0.951729  0.951725  0.951706      model_19  511.418233
1      LSTM  0.900164   0.900253  0.900164  0.900175       model_3  117.564370
0        LR  0.844560   0.845231  0.844560  0.844623      model_28    3.373161
2  MLP SWEM  0.842917   0.843424  0.842915  0.842943      model_31  145.768165
6      SWEM  0.842158   0.843126  0.842159  0.842303  svm_model_20  482.495683
3        NB  0.798433   0.799726  0.798436  0.798372       model_9    0.381395
4       RNN  0.773158   0.773699  0.773161  0.773091       model_8  548.074079